# Generated by Django 4.1.1 on 2022-09-17 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0002_categoria_titulo_delete_filmes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='data_criacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='titulo',
            name='classificacao',
            field=models.IntegerField(null=True),
        ),
    ]
